const words = [
  "alaska",
  "alabama",
  "arkansas",
  "americansamoa",
  "arizona",
  "california",
  "colorado",
  "connecticut",
  "districtofcolumbia",
  "delaware",
  "florida",
  "georgia",
  "guam",
  "hawaii",
  "iowa",
  "idaho",
  "illinois",
  "indiana",
  "kansas",
  "kentucky",
  "louisiana",
  "massachusetts",
  "maryland",
  "maine",
  "michigan",
  "minnesota",
  "missouri",
  "mississippi",
  "montana",
  "northcarolina",
  "northdakota",
  "nebraska",
  "newhampshire",
  "newjersey",
  "newmexico",
  "nevada",
  "newyork",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "puertorico",
  "rhodeisland",
  "southcarolina",
  "southdakota",
  "tennessee",
  "texas",
  "utah",
  "virginia",
  "virginislands",
  "vermont",
  "washington",
  "wisconsin",
  "westvirginia",
  "wyoming",
];

export const useRandomWord = () => {
  const getRandomWord = () => {
    const idx = Math.floor(Math.random() * words.length);
    return words[idx];
  };

  return { getRandomWord };
};
